modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/CreativeMD/PlayerRevive/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="playerrevive"
    logoFile="playerrevive.png"
    version="2.0.28"
    displayName="PlayerRevive"
    displayURL="https://modrinth.com/mod/playerrevive"
    authors="CreativeMD"
    description='''Help your friends in need and revive them.'''

[[dependencies.playerrevive]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.playerrevive]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"

[[dependencies.playerrevive]]
   modId="creativecore"
   type="required"
   ordering="NONE"
   side="BOTH"
   versionRange="[2.12.4,)"

[[mixins]]
   config="playerrevive.mixins.json"

